name: news-embedding-cluster
services:
  azurite:
    container_name: "azurite"
    image: mcr.microsoft.com/azure-storage/azurite
    pull_policy: always
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    networks:
      sb-emulator:
        aliases:
          - "azurite"

  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      SQL_WAIT_INTERVAL: ${SQL_WAIT_INTERVAL}
    depends_on:
      - mssql
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"

  mssql:
    container_name: "mssql"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    networks:
      sb-emulator:
        aliases:
          - "mssql"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"

  # Cosmos DB Emulator (https://github.com/Azure/azure-cosmos-db-emulator-docker)
  # Learn more about the emulator and its limitations here:https://learn.microsoft.com/en-us/azure/cosmos-db/emulator-linux
  cosmosdb:
    container_name: "cosmosdb"
    image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview"
    pull_policy: always
    ports:
      - "8081:8081" # Gateway Endpoint (HTTPS)
      - "1234:1234" # Data Explorer UI (HTTP)
    environment:
      - PROTOCOL=http 
      - PORT=8081
      - ENABLE_EXPLORER=true
      - EXPLORER_PORT=1234
      - DATA_PATH=/data 
    volumes:
      - cosmos-data:/data
    networks:
      sb-emulator:
        aliases:
          - "cosmosdb"

networks:
  sb-emulator:

volumes:
  cosmos-data: